"""AI-generated weekly insights + CSV export (FR-IO-01, FR-IO-02)."""

from __future__ import annotations

from datetime import UTC, datetime

import pandas as pd
import plotly.express as px
import streamlit as st
from finsight_ui.api_client import ApiError
from finsight_ui.state import get_client, require_login

st.set_page_config(page_title="FinSight · Insights", page_icon="💡", layout="wide")
st.title("Insights 💡")

require_login()
client = get_client()

# --- AI insights (real, generated by the backend LLM agent) ------------------
c1, c2 = st.columns([3, 1])
with c1:
    month_value = st.text_input(
        "Mes (YYYY-MM)",
        value=datetime.now(tz=UTC).strftime("%Y-%m"),
        key="insights_month",
        help="Deja el mes actual para ver tus insights de este período.",
    )
with c2:
    st.write("")
    refresh = st.button("Generar insights", use_container_width=True)

insights = st.session_state.get("latest_insights")
if refresh or insights is None:
    try:
        insights = client.get_insights(month=month_value or None)
        st.session_state["latest_insights"] = insights
    except ApiError as err:
        st.warning(f"No se pudieron generar los insights: {err.detail}")
        insights = None

if insights:
    badge = "🤖 Generado por IA" if insights.get("ai_generated") else "📊 Análisis automático"
    st.caption(badge)
    st.markdown(f"**{insights.get('summary', '')}**")
    highlights = insights.get("highlights") or []
    if highlights:
        for h in highlights:
            st.markdown(f"- {h}")

st.divider()

# --- weekly preview (unchanged) ---------------------------------------------
data = st.session_state.get("latest_dashboard")
if data is None:
    try:
        data = client.get_dashboard()
        st.session_state["latest_dashboard"] = data
    except ApiError as err:
        st.warning(f"No se pudo cargar el dashboard: {err.detail}")
        data = {}

by_week = (data or {}).get("by_week") or []
if by_week:
    st.subheader("Vista previa semanal")
    df = pd.DataFrame([{"Semana": w["week_start"], "Monto": float(w["amount"])} for w in by_week])
    fig = px.bar(df, x="Semana", y="Monto")
    fig.update_layout(margin={"t": 10, "b": 10, "l": 10, "r": 10})
    st.plotly_chart(fig, use_container_width=True)

st.divider()
st.subheader("Exportar a CSV")
st.caption("Descarga todos tus gastos como un archivo CSV (FR-IO-01).")

c1, c2 = st.columns(2)
with c1:
    from_date = st.date_input("Desde", value=None, key="csv_from")
with c2:
    to_date = st.date_input("Hasta", value=None, key="csv_to")

today = datetime.now(tz=UTC).date().isoformat()
if st.button("Generar CSV", use_container_width=True):
    try:
        blob = client.get_csv_bytes(
            from_date=from_date or None,
            to_date=to_date or None,
        )
    except ApiError as err:
        st.error(f"No se pudo exportar: {err.detail}")
    else:
        st.session_state["csv_blob"] = blob
        st.session_state["csv_filename"] = f"finsight-expenses-{today}.csv"

if "csv_blob" in st.session_state:
    st.download_button(
        "Descargar CSV",
        data=st.session_state["csv_blob"],
        file_name=st.session_state.get("csv_filename", f"finsight-expenses-{today}.csv"),
        mime="text/csv",
        use_container_width=True,
    )
